spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/issimo_crud
#    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      driver-class-name: com.mysql.jdbc.Driver